### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/antilope#12]
allow users to bookmark sharables

**Comment by vincent-peugnet** [comment]
What I want to store with a bookmark:

A list of sharable bookmarked by an user, and allow him or her to sort by date added.

So I can't just add a `many to many` relationship between sharable and users.

I need to create a `bookmark` entity with the following properties:

### `Bookmark` Entity

- id `int`
- createdAt `datetime`
- sharable `Sharable`
- user `User`

I'd like to but something else, but I don't know what... ^^

do you confirm @n-peugnet ?

**Comment by n-peugnet** [comment]
:+1:

**Comment by vincent-peugnet** [comment]
Closed by https://github.com/vincent-peugnet/antilope/commit/8844358294b4c8e1db0f54de89b90963a214ba1d
