### ISSUE TITLE
dedicated rich text description editing tool

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/antilope#50]
instead of editing sharable description as a part of `/edit`, add a specific interface with a generous editor.

### What I need:

1. display markdown synthax
2. have toolbar for text style
3. have image import tool !?
4. have an easy url tool

In fact, Github editor is almost perfect, I love the image drag n drop function, but it lack of url help wich is cool for beginners I think.

### Selection

- [Toast UI Editor](https://nhn.github.io/tui.editor/latest/tutorial-example02-editor-with-horizontal-preview)
- [stackedit.js](https://github.com/benweet/stackedit.js)
- [hyperMD](https://laobubu.net/HyperMD/#README.md)
- ~simpleMDE~ [Easy Markdown Editor](https://github.com/Ionaru/easy-markdown-editor) lightweight

For example *Toast UI editor* is based on Jquery, and I use jquery query for bootstrap menu and others. Is it a good strategy to use only one main library like this more than many differents @n-peugnet ?

**Comment by n-peugnet** [comment]
As jQuery is only used for the drop down menu and as it is really not optimal and could be done by hand easily, I think it would be better not to rely on jQuery at all, to be able to ditch it someday.

**Comment by n-peugnet** [comment]
Maybe this could be it https://github.com/refactory-id/bootstrap-markdown

Here is a demo http://embed.plnkr.co/atyuBnVNktl8YSfdfPJT/preview

**Comment by vincent-peugnet** [comment]
Hey @n-peugnet , are you up on doing this ?

What should I do to prepare it ?
