### ISSUE TITLE
learn how to deploy in production for alpha version

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/antilope#55]

**Comment by vincent-peugnet** [comment]
https://symfony.com/doc/current/deployment.html

https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by n-peugnet** [comment]
> https://symfony.com/doc/current/deployment.html
> 
> > On a shared hosting platform using the Apache web server, you may need to install the symfony/apache-pack package
> 
> https://symfony.com/doc/current/setup/web_server_configuration.html

I did this in the vhost for the alpha so there is no need for the apache package

**Comment by vincent-peugnet** [comment]
Okay, should we close this issue ?

**Comment by n-peugnet** [comment]
It's up to you, but I think you know well how to do it now

**Comment by vincent-peugnet** [comment]
If @n-peugnet  thinks I know well how to do it, it is time to close the issue
