### ISSUE TITLE
Problem with this migration

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/antilope#56]
https://github.com/vincent-peugnet/antilope/blob/7331a108a35a877a73f62a1ee663fd36d6667a2d/migrations/mysql/Version20210128161954.php#L23

I don't remember what I've done here when correcting a spelling error, but I've broke the migration system. I think I've deleted the original creation of `last_activivy`.

I think I should transform it to `ADD last_activity` instead of `CHANGE` because there are no reference of `last_activy` before.

What do you think @n-peugnet

**Comment by n-peugnet** [comment]
This seems like the way to go indeed. But I didn't check the other migrations

**Comment by n-peugnet** [comment]
A [quick search in GitHub](https://github.com/vincent-peugnet/antilope/search?q=last_activiy) showed that there is indeed no other references to `last_activiy`.

So yes, you should change it with `ADD`.

Remember to always check that the database is in sync with the latest migration before making another (doctrine should warn you about this).

**Comment by vincent-peugnet** [comment]
Closed by 7331a108a35a877a73f62a1ee663fd36d6667a2d
