### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/antilope#61]
At least french for the beta.

https://symfony.com/doc/current/translation.html

**Comment by vincent-peugnet** [comment]
Multi language for content
-----------------------------------

If I want to do a multi language system for the content what should I do ?


My idea would be to add a `content-local` field to each text field in forms. If this options is activated in the instance, the main content will became english and de second one, using local language.

What do you think about it @n-peugnet ?

On workaway.info for example, it's done manually by user typing both language in the description field in most cases.

Also TAGs, and RULEs could have the same system with no problem.

**Comment by n-peugnet** [comment]
Why do you think that multiple language for content would be a good idea ?

This issue was more about having multiple languages for the application, so that the admin can choose once the language of the instance.

**Comment by vincent-peugnet** [comment]
yes it was a diversion of issue !! Okay, I create another one not to pollute this one ;).

> This issue was more about having multiple languages for the application, so that the admin can choose once the language of the instance.

I would have fought more as an user setting.
