### ISSUE TITLE
Search/list sharable improvements

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/antilope#62]
- More links:
  - on the title "un match de ping pong" to the sharable's page
  - on the username "vincent" to the user's page

- Tooltips (title)
  - ~~on the badge "user" to explain what it means~~
  - on the date "created 1 hour ago" to show the real date

![2021-02-10-173632_1121x174_scrot](https://user-images.githubusercontent.com/23519418/107540700-a328f880-6bc6-11eb-9e4c-b01d4c401cae.png)

**Comment by vincent-peugnet** [comment]
More links is the internet n°1  rule

**Comment by vincent-peugnet** [comment]
>     * on the badge "user" to explain what it means

Is'nt it already there ??? For me it's working. Maybe it is not clear enought anyway

**Comment by n-peugnet** [comment]
> >
> > * on the badge "user" to explain what it means
> 
> Is'nt it already there ??? For me it's working. Maybe it is not clear enought anyway

oops sorry you're right
